#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-mustache.java
Version  : 0.9.3
Release  : 1
URL      : https://github.com/spullara/mustache.java/archive/mustache.java-0.9.3.tar.gz
Source0  : https://github.com/spullara/mustache.java/archive/mustache.java-0.9.3.tar.gz
Source1  : https://repo.maven.apache.org/maven2/com/github/spullara/mustache/java/compiler/0.9.3/compiler-0.9.3.jar
Source2  : https://repo.maven.apache.org/maven2/com/github/spullara/mustache/java/compiler/0.9.3/compiler-0.9.3.pom
Source3  : https://repo.maven.apache.org/maven2/com/github/spullara/mustache/java/mustache.java/0.9.3/mustache.java-0.9.3.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-mustache.java-data = %{version}-%{release}
Requires: mvn-mustache.java-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
Mustache.java [![Build Status](https://travis-ci.org/spullara/mustache.java.svg?branch=master)](https://travis-ci.org/spullara/mustache.java)
=============

%package data
Summary: data components for the mvn-mustache.java package.
Group: Data

%description data
data components for the mvn-mustache.java package.


%package license
Summary: license components for the mvn-mustache.java package.
Group: Default

%description license
license components for the mvn-mustache.java package.


%prep
%setup -q -n mustache.java-mustache.java-0.9.3

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-mustache.java
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-mustache.java/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/spullara/mustache/java/compiler/0.9.3
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/github/spullara/mustache/java/compiler/0.9.3/compiler-0.9.3.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/spullara/mustache/java/compiler/0.9.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/github/spullara/mustache/java/compiler/0.9.3/compiler-0.9.3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/github/spullara/mustache/java/mustache.java/0.9.3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/github/spullara/mustache/java/mustache.java/0.9.3/mustache.java-0.9.3.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/github/spullara/mustache/java/compiler/0.9.3/compiler-0.9.3.jar
/usr/share/java/.m2/repository/com/github/spullara/mustache/java/compiler/0.9.3/compiler-0.9.3.pom
/usr/share/java/.m2/repository/com/github/spullara/mustache/java/mustache.java/0.9.3/mustache.java-0.9.3.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-mustache.java/LICENSE
